services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin2025!
      - MARIADB_DATABASE=burger
      - MARIADB_ROOT_PASSWORD=admin2025!
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
  monapache:
    image: iliasblf/monapache
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80
  monubuntu:
    image: iliasblf/monubuntu